env:
  RUBY_VERSION: 3.3.6
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  DATABASE_USER: postgres
  DATABASE_PASSWORD: password

name: Rails tests
on: [push, pull_request]

jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install Postgres client
        run: sudo apt-get update && sudo apt-get install -y libpq-dev
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Create database
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test
      - uses: borales/actions-yarn@v3
        with:
          cmd: install
      - name: Run tests
        run: bundle exec rspec .
      - name: Run Brakeman security scan
        run: brakeman -o brakeman.txt
      - name: Run RuboCop
        run: bundle exec rubocop --force-exclusion vendor/*/** --out rubocop.txt
      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage
      - name: Upload RuboCop report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: rubocop-report
          path: rubocop.txt
      - name: Upload Brakeman report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: brakeman-report
          path: brakeman.txt
