name: Rails Tests

on: [push, pull_request]

env:
  RUBY_VERSION: 3.3.6
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  DATABASE_USER: postgres
  DATABASE_PASSWORD: password

jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Install PostgreSQL client
        run: sudo apt-get install -y libpq-dev

      - name: Install Bundler and Dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Install Yarn and Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Webpacker & JS Dependencies
        run: |
          yarn install
          bundle exec rails webpacker:install
          bundle exec rake jsbundling:install

      - name: Set up Database
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Run RSpec Tests
        run: bundle exec rspec .

      - name: Run Brakeman Security Check
        run: brakeman -o brakeman.txt

      - name: Run Rubocop Linter
        run: bundle exec rubocop --force-exclusion --out rubocop.txt

      - name: Upload Coverage Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-report
          path: coverage

      - name: Upload Rubocop Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: rubocop-report.txt
          path: rubocop.txt

      - name: Upload Brakeman Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: brakeman-report.txt
          path: brakeman.txt
